name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  vitest:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:latest
    steps:
      - name: Install Git and LFS
        run: |
          apt-get update
          apt-get install -y git git-lfs
          git --version
          git lfs --version

      - uses: actions/checkout@v4
        with:
          lfs: false

      - name: Mark Workspace as Safe
        run: git config --system --add safe.directory "$PWD"

      - name: Checkout LFS
        run: git lfs pull
        working-directory: ${{ github.workspace }}

      - name: Install Dependencies
        run: bun install
        working-directory: ${{ github.workspace }}/project

      - name: Run Tests
        run: bun run test
        working-directory: ${{ github.workspace }}/project
